import { component$, useStylesScoped$ } from '@builder.io/qwik'
import styles from './icons.scss?inline'

export default component$(() => {
  useStylesScoped$(styles)

  const iconClasses = [
    'amazonwebservices-original',
    // 'android-plain',
    'ansible-plain',
    // 'apple-original',
    // 'babel-plain',
    'bash-plain',
    // 'bitbucket-original',
    'bootstrap-plain',
    'c-plain',
    // 'canva-original',
    'coffeescript-original',
    // 'composer-line',
    // 'confluence-original',
    'cplusplus-plain',
    'css3-plain',
    'dart-plain',
    'django-plain',
    'docker-plain',
    'doctrine-plain',
    'express-original',
    'figma-plain',
    'flutter-plain',
    'gimp-plain',
    'git-plain',
    // 'github-original',
    // 'gitlab-plain',
    'gradle-plain',
    'heroku-original',
    'html5-plain',
    'inkscape-plain',
    'jamstack-original',
    'java-plain',
    'javascript-plain',
    'jest-plain',
    'jenkins-plain',
    // 'jetbrains-plain',
    'jira-plain',
    'jquery-plain',
    'kotlin-plain',
    'knockout-plain-wordmark',
    'latex-original',
    'less-plain-wordmark',
    'lua-plain',
    // 'linux-plain',
    'materialui-plain',
    'matlab-plain',
    // 'magento-original',
    'markdown-original',
    'mongodb-plain',
    'mysql-plain',
    'nodejs-plain',
    // 'npm-original-wordmark',
    'numpy-original',
    'ocaml-plain',
    'pandas-original',
    'php-plain',
    'phpstorm-plain',
    'postgresql-plain',
    // 'processing-plain',
    'python-plain',
    'r-original',
    'rails-plain',
    'react-original',
    'redis-plain',
    'redux-original',
    'ruby-plain',
    'rstudio-plain',
    'sass-original',
    // 'ssh-original',
    'swift-plain',
    'symfony-original',
    'storybook-plain',
    'tailwindcss-original-wordmark',
    'threejs-original',
    // 'trello-plain',
    'typescript-plain',
    'unity-original',
    'vagrant-plain',
    'vuejs-plain',
    // 'vscode-plain',
    // 'woocommerce-plain',
    'wordpress-plain'
    // 'xcode-plain',
    // 'yarn-plain'
  ]
  const icons = iconClasses.map(iconClass => (
    <span className="icons__icon">
      <i className={`devicon-${iconClass}`}></i>
    </span>
  ))

  return <div className="icons">{icons}</div>
})
